import type { Metadata } from "next";
import { Inter, Inter_Tight } from "next/font/google";
import "./globals.css";

const intersans = Inter({
  variable: "--font-inter-sans",
  subsets: ["latin"],
});

const interLight = Inter_Tight({
  variable: "--font-inter-light",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${intersans.variable} ${interLight.variable} antialiased flex flex-col min-h-screen bg-background text-foreground font-sans mx-36 my-5`}
      >
        {children}
      </body>
    </html>
  );
}
